### ISSUE TITLE
下载成功但文件名错误显示为mailpush_saved_file

### ISSUE THREAD

**Issue by realjackwang** [guo-yong-zhi/MailPush#1]
## 问题
使用默认设置文件下载后存放在根目录，名称为 mailpush_saved_file

起初我以为是没有设置saveto参数，以及中文文件名的关系，后来查看 log.txt 提示 File not found，幡然醒悟

我的`documents`目录下没有`downloads`文件夹，新建一个`downloads`文件夹后问题解决

## 解决
在下载前判断文件夹是否存在，并新增一个mkdir的功能

**Comment by guo-yong-zhi** [comment]
代码里有mkdir：https://github.com/guo-yong-zhi/MailPush/blob/6781ac97c531703f45f83a09dd0e6e9ed0ef2c35/src/fetchfiles.py#L41 所以我不能确定你说的这个问题发生的原因。你可以把完整的log和邮件内容贴出来吗？当然有余力的话更欢迎你直接定位解决问题提PR。: )

**Comment by realjackwang** [comment]
看起来应该是中文文件名的问题，我在电脑上调试一下看看。

完整log：
```
========== 2022-05-14 09:58:29 ==========
* 2022-05-14 09:58:30, login
OK, There are 8 emails in INBOX
OK, There are 3 UNSEEN emails in the past 2 days

** 2022-05-14 09:58:34 **
*************************
* From: ****@mail.com
* To: ****@mail.com
* Subject: 电子书： 2001：太空漫游 : 《太空漫游四部曲》第1部
*************************
[Errno 22] Invalid argument: '/mnt/us/documents/downloads/2001：太空漫游 : 《太空漫游四部曲》第1部 - [英]阿瑟·克拉克.azw3'
/mnt/us/documents/downloads/2001：太空漫游 : 《太空漫游四部曲》第1部 - [英]阿瑟·克拉克.azw3 is illegal. Try filename: /mnt/us/documents/downloads/mailpush_saved_file
- Attachment File Found: 2001：太空漫游 : 《太空漫游四部曲》第1部 - [英]阿瑟·克拉克.azw3. Save it to /mnt/us/documents/downloads/mailpush_saved_file

---------- 2022-05-14 09:58:46 ----------
kill: can't kill pid 10551: No such process
```

邮件内容：
![image](https://user-images.githubusercontent.com/29890029/168422041-8563b9d8-c1bb-4645-ba63-df62303f1c2b.png)

**Comment by guo-yong-zhi** [comment]
我有个怀疑，把41行挪到24行会不会就好了。但我现在没有电脑不能试。

**Comment by realjackwang** [comment]
恩，这样能解决路径的问题，但是我还是不能正常下载，我还在看源码。

**Comment by realjackwang** [comment]
我知道了，我的文件名中有一个英文的冒号，导致抛出异常

**Comment by guo-yong-zhi** [comment]
fixed by https://github.com/guo-yong-zhi/MailPush/commit/1c724e21343eb5afe1b86bc3e085a6674c40cbd2.
