### ISSUE TITLE
Operation failed

### ISSUE THREAD

**Issue by ivanlin9018** [guo-yong-zhi/MailPush#3]
Here is the log.txt:

========== 2024-07-18 19:12:13 ==========
Traceback (most recent call last):
  File "/mnt/us/extensions/MailPush/src/mailpush.py", line 12, in <module>
    config = json.load(open(configfn))
  File "/mnt/us/python3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/mnt/us/python3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/mnt/us/python3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/mnt/us/python3/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 28 (char 64)
kill: can't kill pid 6479: No such process

啥原因咧大佬？python版本不对吗？
Python按README里面下载的，版本是：
0.15.N @ r18981 on 2023-Jan-04 @ 23:54

**Comment by ivanlin9018** [comment]
还有一个问题，下载链接要提供直链对吧。
网盘、Webdav不太行，那么除了Nas，大佬有啥好办法推荐吗

**Comment by ivanlin9018** [comment]
设备是KPW3，已越狱。KUAL、KOreader之类的都可以正常使用。
我想找个依赖于Python3的插件再测试下，不过还没找到。

**Comment by guo-yong-zhi** [comment]
> JSONDecodeError: Expecting ',' delimiter: line 3 column 28

python安装应该没问题，报错说你config.json第三行最后少打了一个逗号。

---
需要直链。我一般就是下载论文pdf用这个链接功能。已有小文件直接加到附件里发送。如果文件很大(>20M)，我用 https://github.com/guo-yong-zhi/kindle-filebrowser 传。

**Comment by ivanlin9018** [comment]
> > JSONDecodeError: Expecting ',' delimiter: line 3 column 28
> 
> python安装应该没问题，报错说你config.json第三行最后少打了一个逗号。
> 
> 需要直链。我一般就是下载论文pdf用这个链接功能。已有小文件直接加到附件里发送。如果文件很大(>20M)，我用 https://github.com/guo-yong-zhi/kindle-filebrowser 传。

大佬，我找到原因了。不是少了个`,`，是因为密码里有个英文双引号。。。，密码是keepass生成的，就没想到。
